terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "aws" {
  region = var.region
}

# ═══════════════════════════════════════════════════════════════════════════════
# AWS RDS Custom for SQL Server — the Entitle-COMPATIBLE managed SQL Server on AWS.
#
# Unlike standard RDS for SQL Server (terraform/db_sqlserver), RDS Custom grants the
# master user `sysadmin` and gives OS access, so Entitle's Microsoft SQL Server
# connector can manage it (standard mode = sysadmin). Standard RDS reserves sysadmin
# for the internal `rdsa` account, which is why db_sqlserver is NOT Entitle-viable.
#
# SCAFFOLD (live provisioning DEFERRED): RDS Custom has real prerequisites that are
# one-time setup, not created here — see docs/design/entitle-compatible-sqlserver.md:
#   * a Custom Engine Version (CEV, engine "custom-sqlserver-*") built from your own
#     SQL Server installation media in an S3 bucket — there is NO AWS-provided CEV, so
#     `engine_version` has no default and MUST be supplied (aws_rds_custom_sqlserver_cev);
#   * an IAM instance profile with the AWS-managed RDS Custom policy
#     (`custom_iam_instance_profile`);
#   * a customer-managed KMS key (`kms_key_id`) — RDS Custom requires encryption;
#   * a supported instance class — RDS Custom does NOT support db.t3.* (use db.r5.* /
#     db.m5.* and up).
# Always private (publicly_accessible = false), reached only via the PRA mssql tunnel.
# ═══════════════════════════════════════════════════════════════════════════════

# ── Variables ────────────────────────────────────────────────────────────────

variable "region" {
  type        = string
  description = "AWS region for the RDS Custom instance"
}

variable "identifier" {
  type        = string
  description = "RDS instance identifier (unique per region)"
}

variable "engine" {
  type        = string
  default     = "custom-sqlserver-se"
  description = "RDS Custom SQL Server edition engine (custom-sqlserver-se / -ee / -web)."
}

variable "engine_version" {
  type = string
  # A Custom Engine Version you built from your SQL Server media (e.g.
  # "15.00.4249.2.cev-1"). REQUIRED — there is no AWS default CEV. The dashboard maps
  # the aws_rds_custom_sqlserver_cev config key onto this.
  description = "Custom Engine Version (CEV) identifier. REQUIRED — no AWS default."
}

variable "instance_class" {
  type        = string
  default     = "db.r5.large"
  description = "RDS Custom instance class. RDS Custom does NOT support db.t3.* — use db.r5.* / db.m5.* and up."
}

variable "allocated_storage" {
  type        = number
  default     = 20
  description = "Allocated storage in GiB"
}

variable "master_username" {
  type        = string
  description = "Master (admin) username — granted sysadmin on RDS Custom"
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Master (admin) password, generated by the dashboard at provision"
}

variable "db_subnet_group_name" {
  type        = string
  description = "DB subnet group placing the instance in private subnets"
}

variable "vpc_security_group_ids" {
  type        = list(string)
  default     = []
  description = "Security groups controlling access (Jumpoint/PRA reachability only)"
}

variable "custom_iam_instance_profile" {
  type = string
  # An IAM instance profile whose role carries the AWS-managed RDS Custom policy.
  # REQUIRED for RDS Custom. The dashboard maps aws_rds_custom_instance_profile here.
  description = "IAM instance profile for RDS Custom. REQUIRED."
}

variable "kms_key_id" {
  type = string
  # Customer-managed KMS key ARN — RDS Custom requires storage encryption with a CMK.
  # The dashboard maps aws_rds_custom_kms_key_id here.
  description = "Customer-managed KMS key ARN for storage encryption. REQUIRED for RDS Custom."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (managed-by, clouddb-id)"
}

# ── Resource — always private (no public endpoint) ──────────────────────────
# Like standard RDS SQL Server, RDS Custom does NOT accept db_name at creation — you
# connect to the `master` system DB (the PRA mssql tunnel targets master). The
# distinguishing bits vs db_sqlserver are the custom-* engine + CEV, the mandatory
# custom_iam_instance_profile, and CMK storage encryption.

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = var.engine
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  username          = var.master_username
  password          = var.master_password

  publicly_accessible         = false
  db_subnet_group_name        = var.db_subnet_group_name
  vpc_security_group_ids      = var.vpc_security_group_ids
  custom_iam_instance_profile = var.custom_iam_instance_profile

  storage_encrypted = true
  kms_key_id        = var.kms_key_id

  skip_final_snapshot = true
  apply_immediately   = true
  deletion_protection = false

  tags = var.tags
}

# ── Outputs (match the module contract: instance_id / private_host / port) ────

output "instance_id" {
  value       = aws_db_instance.this.id
  description = "RDS instance identifier / resource id"
}

output "private_host" {
  value       = aws_db_instance.this.address
  description = "Private endpoint host — reached only via the PRA tunnel"
}

output "port" {
  value       = aws_db_instance.this.port
  description = "Database port (SQL Server: 1433)"
}
