terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "azurerm" {
  features {}
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "resource_group_name" {
  type        = string
  description = "Resource group the Flexible Server lands in"
}

variable "location" {
  type        = string
  description = "Azure region (e.g. eastus)"
}

variable "identifier" {
  type        = string
  description = "Flexible Server name (globally unique, lowercase letters/digits/hyphens)"
}

variable "administrator_login" {
  type        = string
  description = "Server admin username"
}

variable "administrator_password" {
  type        = string
  sensitive   = true
  description = "Server admin password, generated by the dashboard at provision"
}

variable "sku_name" {
  type        = string
  default     = "B_Standard_B1ms"
  description = "Flexible Server SKU (e.g. B_Standard_B1ms, GP_Standard_D2s_v3)"
}

variable "storage_mb" {
  type        = number
  default     = 32768
  description = "Storage in MB (min 32768)"
}

variable "postgres_version" {
  type        = string
  default     = "16"
  description = "PostgreSQL major version"
}

variable "db_name" {
  type        = string
  description = "Initial database name"
}

variable "delegated_subnet_id" {
  type        = string
  description = "Subnet delegated to Microsoft.DBforPostgreSQL/flexibleServers (VNet-integrated private access). The sandbox creates + delegates it."
}

variable "private_dns_zone_id" {
  type        = string
  description = "Private DNS zone (…postgres.database.azure.com) linked to the VNet. The sandbox creates + links it."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (managed-by, clouddb-id)"
}

# ── Resource — always private (VNet-integrated, no public endpoint) ──────────
# delegated_subnet_id + private_dns_zone_id make this VNet-integrated: the server
# has NO public endpoint and is reachable only inside the VNet — i.e. only via
# the PRA protocol-tunnel jump on the jumpoint VM (Phase 2). Never add a public
# access rule.

resource "azurerm_postgresql_flexible_server" "this" {
  name                   = var.identifier
  resource_group_name    = var.resource_group_name
  location               = var.location
  version                = var.postgres_version
  administrator_login    = var.administrator_login
  administrator_password = var.administrator_password
  sku_name               = var.sku_name
  storage_mb             = var.storage_mb
  delegated_subnet_id    = var.delegated_subnet_id
  private_dns_zone_id    = var.private_dns_zone_id

  # VNet integration (delegated_subnet_id) is mutually exclusive with public
  # network access: Azure rejects the create with
  # ConflictingPublicNetworkAccessAndVirtualNetworkConfiguration otherwise. The
  # provider defaults this to true, so the private (VNet-integrated) server this
  # module always builds must set it false explicitly.
  public_network_access_enabled = false

  tags = var.tags
}

# Disable forced SSL — the PRA protocol tunnel proxies the cleartext PostgreSQL
# wire protocol (to inject the Vault credential + record the session) and has no
# backend-TLS option. Flexible Server defaults require_secure_transport=ON, which
# rejects the tunnel's cleartext jumpoint→DB connection. (AWS analog: rds.force_ssl=0;
# GCP analog: ssl_mode=ALLOW_UNENCRYPTED_AND_ENCRYPTED.) Client→jumpoint is still
# PRA-encrypted; only the intra-VNet jumpoint→DB hop is cleartext.
resource "azurerm_postgresql_flexible_server_configuration" "no_ssl" {
  name      = "require_secure_transport"
  server_id = azurerm_postgresql_flexible_server.this.id
  value     = "OFF"
}

resource "azurerm_postgresql_flexible_server_database" "this" {
  name      = var.db_name
  server_id = azurerm_postgresql_flexible_server.this.id
  charset   = "UTF8"
  collation = "en_US.utf8"
}

# ── Outputs (match the AWS module contract: instance_id / private_host / port) ─

output "instance_id" {
  value       = azurerm_postgresql_flexible_server.this.id
  description = "Flexible Server resource id"
}

output "private_host" {
  value       = azurerm_postgresql_flexible_server.this.fqdn
  description = "Private FQDN — resolves inside the VNet, reached only via the PRA tunnel"
}

output "port" {
  value       = 5432
  description = "Database port (PostgreSQL)"
}
