terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "aws" {
  region = var.region
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "region" {
  type        = string
  description = "AWS region for the RDS instance"
}

variable "identifier" {
  type        = string
  description = "RDS instance identifier (unique per region)"
}

variable "instance_class" {
  type        = string
  default     = "db.t3.micro"
  description = "RDS instance class"
}

variable "allocated_storage" {
  type        = number
  default     = 20
  description = "Allocated storage in GiB"
}

variable "engine_version" {
  type        = string
  default     = "16"
  description = "PostgreSQL major engine version"
}

variable "db_name" {
  type        = string
  description = "Initial database name"
}

variable "master_username" {
  type        = string
  description = "Master (admin) username"
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Master (admin) password, generated by the dashboard at provision"
}

variable "db_subnet_group_name" {
  type        = string
  description = "DB subnet group placing the instance in private subnets"
}

variable "vpc_security_group_ids" {
  type        = list(string)
  default     = []
  description = "Security groups controlling access (Jumpoint/PRA reachability only)"
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (workgroup, managed-by)"
}

# ── Resource — always private (no public endpoint) ──────────────────────────
# publicly_accessible = false is load-bearing: the only path in is the PRA
# protocol-tunnel jump (Phase 2, via the beyondtrust/sra provider). Never
# expose a public endpoint.

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = "postgres"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  db_name           = var.db_name
  username          = var.master_username
  password          = var.master_password

  publicly_accessible    = false
  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids  = var.vpc_security_group_ids

  skip_final_snapshot = true
  apply_immediately   = true
  deletion_protection = false

  tags = var.tags
}

# ── Outputs ─────────────────────────────────────────────────────────────────

output "instance_id" {
  value       = aws_db_instance.this.id
  description = "RDS instance identifier / resource id"
}

output "private_host" {
  value       = aws_db_instance.this.address
  description = "Private endpoint host — reached only via the PRA tunnel"
}

output "port" {
  value       = aws_db_instance.this.port
  description = "Database port"
}
