terraform {
  required_providers {
    oci = {
      source  = "oracle/oci"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

# Credentials arrive as TF_VAR_* from services/terraform_provider_env.oci_env()
# (the same API-key signing quad the dashboard uses). Blank vars → the provider
# falls back to ~/.oci/config / instance principals.
provider "oci" {
  tenancy_ocid         = var.tenancy_ocid
  user_ocid            = var.user_ocid
  fingerprint          = var.fingerprint
  private_key          = var.private_key
  private_key_password = var.private_key_passphrase
  region               = var.region
}

# ── Provider credential variables (TF_VAR_*) ─────────────────────────────────
variable "tenancy_ocid" {
  type    = string
  default = ""
}
variable "user_ocid" {
  type    = string
  default = ""
}
variable "fingerprint" {
  type    = string
  default = ""
}
variable "private_key" {
  type      = string
  default   = ""
  sensitive = true
}
variable "private_key_passphrase" {
  type      = string
  default   = ""
  sensitive = true
}
variable "region" {
  type = string
}

# ── Autonomous Database variables ────────────────────────────────────────────
variable "compartment_ocid" {
  type        = string
  description = "Compartment the Autonomous Database lands in"
}

variable "identifier" {
  type        = string
  description = "Display name (human-readable; may contain hyphens)"
}

variable "db_name" {
  type        = string
  description = "Autonomous DB name — <=14 chars, alphanumeric, letter-led (no hyphens/underscores)"
}

variable "admin_password" {
  type        = string
  sensitive   = true
  description = "ADMIN password (12-30 chars, upper+lower+digit; generated by the dashboard)"
}

variable "db_workload" {
  type        = string
  default     = "OLTP"
  description = "OLTP = Autonomous Transaction Processing (ATP); DW = Autonomous Data Warehouse (ADW)"
}

variable "is_free_tier" {
  type        = bool
  default     = true
  description = "Always-Free ADB (1 OCPU / 20 GB, public endpoint, mTLS-optional). Free tier CANNOT use a private endpoint — leave subnet_ocid blank."
}

variable "cpu_core_count" {
  type        = number
  default     = 1
  description = "OCPUs (ignored/forced to 1 when is_free_tier)"
}

variable "data_storage_size_in_tbs" {
  type        = number
  default     = 1
  description = "Storage in TB (ignored/forced to the free 20 GB when is_free_tier)"
}

variable "subnet_ocid" {
  type        = string
  default     = ""
  description = "PRIVATE-endpoint subnet (paid ADB only). Blank → public endpoint reached via the PRA tcp tunnel from the public-subnet jumpoint."
}

variable "is_mtls_connection_required" {
  type        = bool
  default     = false
  # The DB is reached only through a BeyondTrust PRA tcp protocol tunnel, which
  # proxies the wire protocol and can't present a client wallet — so mTLS is
  # disabled and a plain TLS connection (no wallet) is accepted. The
  # client→jumpoint hop is still PRA-encrypted.
  description = "false lets the PRA tcp tunnel connect over TLS without a client wallet"
}

variable "freeform_tags" {
  type        = map(string)
  default     = {}
  description = "Freeform tags (managed-by, clouddb-id)"
}

# ── Resource ─────────────────────────────────────────────────────────────────
resource "oci_database_autonomous_database" "this" {
  compartment_id           = var.compartment_ocid
  db_name                  = var.db_name
  display_name             = var.identifier
  admin_password           = var.admin_password
  db_workload              = var.db_workload
  is_free_tier             = var.is_free_tier
  cpu_core_count           = var.is_free_tier ? 1 : var.cpu_core_count
  data_storage_size_in_tbs = var.is_free_tier ? 1 : var.data_storage_size_in_tbs

  # Private endpoint only when explicitly requested AND paid (Always-Free ADB
  # cannot be placed in a VCN). Otherwise the ADB is public.
  subnet_id                   = (!var.is_free_tier && var.subnet_ocid != "") ? var.subnet_ocid : null
  is_mtls_connection_required = var.is_mtls_connection_required

  freeform_tags = var.freeform_tags
}

# ── Outputs (match the DB module contract: instance_id / private_host / port) ─
locals {
  # A public ADB has no single host attribute; the host is embedded in each TNS
  # connection descriptor. Extract it from the "medium" profile (best-effort).
  medium_cs = try(oci_database_autonomous_database.this.connection_strings[0].medium, "")
  cs_host   = try(regex("(?i)HOST=([A-Za-z0-9._-]+)", local.medium_cs)[0], "")
  host      = (!var.is_free_tier && var.subnet_ocid != "") ? try(oci_database_autonomous_database.this.private_endpoint_ip, "") : local.cs_host
}

output "instance_id" {
  value       = oci_database_autonomous_database.this.id
  description = "Autonomous Database OCID"
}

output "private_host" {
  value       = local.host
  description = "Connection host — the private-endpoint IP (paid) or the public TLS host (free tier). Reached via the PRA tcp tunnel."
}

output "port" {
  value       = 1521
  description = "TLS listener port (no-wallet TLS). mTLS would be 1522."
}
