terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      # MySQL 8.4 — whose admin is born on caching_sha2_password (required by the PRA
      # MySQL tunnel; 8.0.21's admin is mysql_native_password, which PRA rejects) — was
      # added to azurerm_mysql_flexible_server only in provider v4.55.0 (#31099). 3.x
      # caps the version enum at 5.7/8.0.21. Scoped to THIS module; db_azure_postgres
      # and azure_vm stay on ~> 3.0 (separate root modules resolve their own provider).
      version = ">= 4.55.0, < 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "azurerm" {
  features {}
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "resource_group_name" {
  type        = string
  description = "Resource group the Flexible Server lands in"
}

variable "location" {
  type        = string
  description = "Azure region (e.g. eastus)"
}

variable "identifier" {
  type        = string
  description = "Flexible Server name (globally unique, lowercase letters/digits/hyphens)"
}

variable "administrator_login" {
  type        = string
  description = "Server admin username"
}

variable "administrator_password" {
  type        = string
  sensitive   = true
  description = "Server admin password, generated by the dashboard at provision"
}

variable "sku_name" {
  type        = string
  default     = "B_Standard_B1ms"
  description = "Flexible Server SKU (e.g. B_Standard_B1ms, GP_Standard_D2ds_v4)"
}

variable "storage_mb" {
  type        = number
  default     = 32768
  description = "Storage in MB (converted to GiB for the MySQL storage block; min 20 GiB)"
}

variable "mysql_version" {
  type        = string
  default     = "8.4"
  description = "MySQL Flexible Server version. Must be 8.4: Azure 8.0.21 defaults default_authentication_plugin to mysql_native_password, so the admin login is created on that legacy plugin — and the PRA MySQL tunnel rejects it ('Unsupported plugin offered from server: mysql_native_password -- reconfigure server for caching_sha2_password'). Flipping the server parameter doesn't help (it only affects newly-created users, not the existing admin). MySQL 8.4 drops mysql_native_password as a default, so the admin is born on caching_sha2_password. (AWS analog: RDS MySQL 8.4.)"
}

variable "db_name" {
  type        = string
  description = "Initial database name"
}

variable "delegated_subnet_id" {
  type        = string
  description = "Subnet delegated to Microsoft.DBforMySQL/flexibleServers (VNet-integrated private access). The sandbox creates + delegates it."
}

variable "private_dns_zone_id" {
  type        = string
  description = "Private DNS zone (…mysql.database.azure.com) linked to the VNet. The sandbox creates + links it."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (managed-by, clouddb-id)"
}

# ── Resource — always private (VNet-integrated, no public endpoint) ──────────
# delegated_subnet_id + private_dns_zone_id make this VNet-integrated: the server
# has NO public endpoint and is reachable only inside the VNet — i.e. only via the
# PRA protocol-tunnel jump on the jumpoint VM. NOTE: unlike the postgres flexible
# server, azurerm_mysql_flexible_server.public_network_access_enabled is COMPUTED
# (not settable) — a delegated subnet makes it private automatically, so it's omitted.

resource "azurerm_mysql_flexible_server" "this" {
  name                   = var.identifier
  resource_group_name    = var.resource_group_name
  location               = var.location
  version                = var.mysql_version
  administrator_login    = var.administrator_login
  administrator_password = var.administrator_password
  sku_name               = var.sku_name
  delegated_subnet_id    = var.delegated_subnet_id
  private_dns_zone_id    = var.private_dns_zone_id

  # MySQL flexible server takes storage as a block (size in GiB), unlike the
  # postgres server's flat storage_mb argument.
  storage {
    size_gb = floor(var.storage_mb / 1024)
  }

  tags = var.tags
}

# Disable forced SSL — the PRA protocol tunnel proxies the cleartext MySQL wire
# protocol (to inject the Vault credential + record the session) and has no
# backend-TLS option. Flexible Server defaults require_secure_transport=ON, which
# rejects the tunnel's cleartext jumpoint→DB connection. (AWS analog: a
# require_secure_transport=0 parameter group; GCP analog: ssl_mode.) The MySQL
# configuration resource keys on server_name + resource_group_name (the postgres
# one used server_id).
resource "azurerm_mysql_flexible_server_configuration" "no_ssl" {
  name                = "require_secure_transport"
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_flexible_server.this.name
  value               = "OFF"
}

resource "azurerm_mysql_flexible_database" "this" {
  name                = var.db_name
  resource_group_name = var.resource_group_name
  server_name         = azurerm_mysql_flexible_server.this.name
  charset             = "utf8mb4"
  collation           = "utf8mb4_general_ci"
}

# ── Outputs (match the AWS module contract: instance_id / private_host / port) ─

output "instance_id" {
  value       = azurerm_mysql_flexible_server.this.id
  description = "Flexible Server resource id"
}

output "private_host" {
  value       = azurerm_mysql_flexible_server.this.fqdn
  description = "Private FQDN — resolves inside the VNet, reached only via the PRA tunnel"
}

output "port" {
  value       = 3306
  description = "Database port (MySQL)"
}
