"""Regression: the BeyondTrust doc hub stays a hub, and stays true.

`docs/integrations/beyondtrust.md` was a 662-line single page covering three products. It
is now a thin hub in front of `password-safe.md`, `privileged-remote-access.md` and
`epml.md`. Two things the existing doc tests cannot see:

  * `test_docs_anchors` proves every link *resolves*; nothing proves a required link
    *exists*. A hub that quietly loses a product page — or a half-finished split that
    never adds one — passes every test in the suite.
  * The hub used to assert that Password Safe, PRA and EPM-L "are controlled by the single
    `beyondtrust_enabled` flag". That sentence is the exact falsehood the split exists to
    remove, and a doc test is the only thing that can pin its replacement.

Deliberately NOT a repo-wide "no doc mentions beyondtrust_enabled" sweep: the hub has to
name the retired key to explain the upgrade path, and a repo-wide version would couple
this file to the app-side rename.

Runs under pytest, or standalone:
    python tests/test_beyondtrust_doc_split.py
"""
import os
import re
import sys

_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
_DOCS = os.path.join(_ROOT, "docs", "integrations")
_HUB = os.path.join(_DOCS, "beyondtrust.md")

PRODUCT_PAGES = ("password-safe.md", "privileged-remote-access.md", "epml.md",
                 "entitle.md")
FLAGS = ("password_safe_enabled", "pra_enabled", "epml_enabled")


def _read(path):
    with open(path, encoding="utf-8") as fh:
        return fh.read()


def test_the_product_pages_exist():
    """The in-app index is generated by rglob, so a missing file is simply an absent
    sidebar entry — no error anywhere."""
    for page in PRODUCT_PAGES:
        path = os.path.join(_DOCS, page)
        assert os.path.exists(path), f"docs/integrations/{page} is missing"
        assert len(_read(path)) > 2000, (
            f"docs/integrations/{page} is a stub; the split moved content, it did not "
            f"leave placeholders")


def test_the_hub_links_to_every_product_page():
    hub = _read(_HUB)
    for page in PRODUCT_PAGES:
        assert f"]({page})" in hub, (
            f"the hub no longer links to {page}, so that product is only reachable by "
            f"guessing the URL — the hub's whole job is routing")


def test_the_hub_names_all_three_flags():
    """The replacement for the deleted single-flag claim. If someone reverts the prose to
    'controlled by the single beyondtrust_enabled flag', this fails."""
    hub = _read(_HUB)
    for flag in FLAGS:
        assert flag in hub, (
            f"the hub does not mention `{flag}`; a reader cannot tell which flag gates "
            f"which product")
    # Present tense only. The hub legitimately explains, in the past tense, that the three
    # *used to* share one flag — that paragraph is the upgrade note. What must not come
    # back is a claim that they still do.
    assert not re.search(
        r"(are|is)\s+(controlled|gated)\s+by\s+the\s+(same|single)\s+`?beyondtrust_enabled",
        hub), ("the hub still claims the products share a single flag — that is the "
               "falsehood the split removed")
    assert not re.search(r"same\s+`?beyondtrust_enabled`?\s+flag", hub), (
        "the hub still says a product is gated by the same flag as another")


def test_the_hub_kept_the_cross_product_content():
    """The hub is not a link list: it holds the image-prep story, which is keyed to an
    artifact (one bt-ready run prepares all three products) rather than to any one of
    them. Three sites link into its anchor."""
    hub = _read(_HUB)
    assert "## Preparing images for BT management" in hub, (
        "the image-prep section left the hub; it belongs to no single product, and "
        "privileged-remote-access.md links into its anchor")
    for var in ("BT_ADMIN_USER", "BT_PRA_CA_PUBKEY", "BT_EPML_URL"):
        assert var in hub, (
            f"{var} left the hub's env-var table — those vars go into one Packer build "
            f"form, so splitting the table matches nothing the operator sees")


def test_each_product_page_names_its_own_flag():
    """A reader landing directly on a product page has to learn what gates it."""
    for page, flag in (("password-safe.md", "password_safe_enabled"),
                       ("privileged-remote-access.md", "pra_enabled"),
                       ("epml.md", "epml_enabled")):
        body = _read(os.path.join(_DOCS, page))
        assert flag in body, f"docs/integrations/{page} never names `{flag}`"


def test_the_token_rotation_anchor_survived_the_move():
    """Three sites depend on this exact slug — docs/kubernetes.md, settings.html and
    k8s/index.html. The heading text was kept byte-identical on purpose so the move was a
    path-only edit; renaming it now breaks all three (test_app_docs_links catches two)."""
    ps = _read(os.path.join(_DOCS, "password-safe.md"))
    assert "## Kubernetes ServiceAccount token rotation" in ps, (
        "the token-rotation heading changed; its slug is depended on by "
        "docs/kubernetes.md, settings.html and k8s/index.html")


def test_no_doc_points_at_a_moved_section_of_the_hub():
    """The hub still returns 200, so a link to a section that moved out of it resolves to
    the page and lands the reader at the top — test_app_docs_links only catches the
    fragment half, and only for templates."""
    stale = ("beyondtrust.md#kubernetes-serviceaccount-token-rotation",
             "beyondtrust.md#password-safe-vm-onboarding-managed-systems",
             "beyondtrust.md#importing-databases-from-password-safe",
             "beyondtrust#kubernetes-serviceaccount-token-rotation")
    offenders = []
    for root in (os.path.join(_ROOT, "docs"), os.path.join(_ROOT, "web_dashboard"),
                 os.path.join(_ROOT, "examples")):
        for dirpath, dirnames, filenames in os.walk(root):
            dirnames[:] = [d for d in dirnames if d != "__pycache__"]
            for fn in filenames:
                if not fn.endswith((".md", ".html", ".py")):
                    continue
                path = os.path.join(dirpath, fn)
                body = _read(path)
                for frag in stale:
                    if frag in body:
                        offenders.append(f"{os.path.relpath(path, _ROOT)} -> {frag}")
    assert not offenders, (
        "these point at hub sections that moved into a product page:\n  "
        + "\n  ".join(offenders))


if __name__ == "__main__":
    fns = [v for k, v in sorted(globals().items()) if k.startswith("test_")]
    failures = 0
    for fn in fns:
        try:
            fn()
            print(f"ok   {fn.__name__}")
        except Exception as e:  # noqa: BLE001
            failures += 1
            print(f"FAIL {fn.__name__}: {e}")
    print(f"\n{len(fns) - failures}/{len(fns)} passed")
    sys.exit(1 if failures else 0)
