terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "azurerm" {
  features {}
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "resource_group_name" {
  type        = string
  description = "Resource group the SQL server + database + private endpoint land in"
}

variable "location" {
  type        = string
  description = "Azure region (e.g. eastus)"
}

variable "identifier" {
  type        = string
  description = "Logical SQL Server name (globally unique, lowercase letters/digits/hyphens)"
}

variable "administrator_login" {
  type        = string
  description = "SQL Server admin username"
}

variable "administrator_password" {
  type        = string
  sensitive   = true
  description = "SQL Server admin password, generated by the dashboard at provision"
}

variable "sku_name" {
  type        = string
  default     = "Basic"
  description = "Azure SQL Database SKU (Basic / S0 / S1 / …). Basic is the cheapest, fine for a sandbox."
}

variable "db_name" {
  type        = string
  description = "Initial database name"
}

variable "subnet_id" {
  type        = string
  description = "Subnet for the private endpoint — a plain (NON-delegated) subnet with PE network policies disabled. The sandbox creates it."
}

variable "private_dns_zone_id" {
  type        = string
  description = "Private DNS zone privatelink.database.windows.net, linked to the VNet. The sandbox creates + links it; the PE registers the server's A record here so <name>.database.windows.net resolves to the private IP inside the VNet."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (managed-by, clouddb-id)"
}

# ── Resources — always private (no public endpoint) ──────────────────────────
# Azure SQL has NO "flexible server" / delegated-subnet model like Postgres/MySQL.
# Privacy is via a Private Endpoint into a sandbox subnet + the
# privatelink.database.windows.net private DNS zone: public_network_access_enabled =
# false closes the public endpoint, and the PE + DNS zone make the server's
# <name>.database.windows.net FQDN resolve to a private IP inside the VNet — the only
# path in is the PRA protocol-tunnel jump (tunnel_type=mssql) on the jumpoint VM.
# NOTE: Azure SQL ALWAYS encrypts (TLS) and cannot be set to cleartext (unlike the
# Postgres/MySQL require_secure_transport=OFF knob). This works anyway because the PRA
# mssql tunnel is TDS-aware and does TLS to the backend itself — it does not need a
# cleartext backend, which is exactly why SQL Server reaches all three clouds.

resource "azurerm_mssql_server" "this" {
  name                          = var.identifier
  resource_group_name           = var.resource_group_name
  location                      = var.location
  version                       = "12.0"
  administrator_login           = var.administrator_login
  administrator_login_password  = var.administrator_password
  public_network_access_enabled = false
  minimum_tls_version           = "1.2"
  tags                          = var.tags
}

resource "azurerm_mssql_database" "this" {
  name      = var.db_name
  server_id = azurerm_mssql_server.this.id
  sku_name  = var.sku_name
  tags      = var.tags
}

# Private Endpoint + DNS: gives the server a private IP in the VNet and registers its
# FQDN in privatelink.database.windows.net so the jumpoint resolves it privately.
resource "azurerm_private_endpoint" "this" {
  name                = "${var.identifier}-pe"
  location            = var.location
  resource_group_name = var.resource_group_name
  subnet_id           = var.subnet_id

  private_service_connection {
    name                           = "${var.identifier}-psc"
    private_connection_resource_id = azurerm_mssql_server.this.id
    subresource_names              = ["sqlServer"]
    is_manual_connection           = false
  }

  private_dns_zone_group {
    name                 = "default"
    private_dns_zone_ids = [var.private_dns_zone_id]
  }

  tags = var.tags
}

# ── Outputs (match the module contract: instance_id / private_host / port) ────

output "instance_id" {
  value       = azurerm_mssql_server.this.id
  description = "SQL Server resource id"
}

output "private_host" {
  value       = azurerm_mssql_server.this.fully_qualified_domain_name
  description = "Server FQDN (<name>.database.windows.net) — resolves to the PE private IP inside the VNet"
}

output "port" {
  value       = 1433
  description = "Database port (SQL Server)"
}
