terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "aws" {
  region = var.region
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "region" {
  type        = string
  description = "AWS region for the RDS instance"
}

variable "identifier" {
  type        = string
  description = "RDS instance identifier (unique per region)"
}

variable "instance_class" {
  type        = string
  default     = "db.t3.micro"
  description = "RDS instance class"
}

variable "allocated_storage" {
  type        = number
  default     = 20
  description = "Allocated storage in GiB"
}

variable "engine_version" {
  type        = string
  default     = "8.0"
  description = "MySQL major (or major.minor) engine version. Keep aligned with the parameter group family (8.0 ↔ mysql8.0)."
}

variable "db_name" {
  type        = string
  description = "Initial database name"
}

variable "master_username" {
  type        = string
  description = "Master (admin) username"
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Master (admin) password, generated by the dashboard at provision"
}

variable "db_subnet_group_name" {
  type        = string
  description = "DB subnet group placing the instance in private subnets"
}

variable "vpc_security_group_ids" {
  type        = list(string)
  default     = []
  description = "Security groups controlling access (Jumpoint/PRA reachability only)"
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (workgroup, managed-by)"
}

variable "parameter_group_name" {
  type    = string
  default = ""
  # Existing DB parameter group to attach. The managed DB is reached ONLY
  # through a BeyondTrust PRA *protocol* tunnel, which proxies the cleartext
  # MySQL wire protocol (that is how it injects the Vault credential and records
  # the session) — the sra_my_sql_tunnel_jump has no backend-TLS option. A server
  # with require_secure_transport=ON rejects the tunnel's plaintext jumpoint→RDS
  # connection. The sandbox pre-creates a mysql8.0-family group with
  # require_secure_transport=0 and passes its name here. We REFERENCE (not create)
  # it on purpose: the scoped dashboard IAM user can't create parameter groups.
  # Empty = RDS default group — fine for non-PRA access models. (PostgreSQL analog:
  # rds.force_ssl=0, which does not exist for MySQL.)
  description = "Existing DB parameter group (e.g. require_secure_transport=0 for the PRA tunnel). Empty = RDS default."
}

# ── Resource — always private (no public endpoint) ──────────────────────────
# publicly_accessible = false is load-bearing: the only path in is the PRA
# protocol-tunnel jump (via the beyondtrust/sra provider). Never expose a public
# endpoint.

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = "mysql"
  engine_version = var.engine_version
  instance_class = var.instance_class

  allocated_storage = var.allocated_storage
  db_name           = var.db_name
  username          = var.master_username
  password          = var.master_password

  publicly_accessible    = false
  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids  = var.vpc_security_group_ids
  parameter_group_name    = var.parameter_group_name != "" ? var.parameter_group_name : null

  skip_final_snapshot = true
  apply_immediately   = true
  deletion_protection = false

  tags = var.tags
}

# ── Outputs ─────────────────────────────────────────────────────────────────

output "instance_id" {
  value       = aws_db_instance.this.id
  description = "RDS instance identifier / resource id"
}

output "private_host" {
  value       = aws_db_instance.this.address
  description = "Private endpoint host — reached only via the PRA tunnel"
}

output "port" {
  value       = aws_db_instance.this.port
  description = "Database port (MySQL: 3306)"
}
