terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "aws" {
  region = var.region
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "region" {
  type        = string
  description = "AWS region for the RDS instance"
}

variable "identifier" {
  type        = string
  description = "RDS instance identifier (unique per region)"
}

variable "instance_class" {
  type        = string
  default     = "db.t3.small"
  description = "RDS instance class. SQL Server needs >=2 GiB RAM, so db.t3.small is the practical minimum (db.t3.micro is too small)."
}

variable "allocated_storage" {
  type        = number
  default     = 20
  description = "Allocated storage in GiB (RDS SQL Server minimum is 20)"
}

variable "engine_version" {
  type    = string
  default = ""
  # SQL Server engine version (e.g. "16.00" for SQL Server 2022). Empty lets RDS
  # pick the default version for the sqlserver-ex engine. If you pin a version AND
  # attach a parameter_group_name, keep its family aligned (16.00 <-> sqlserver-ex-16.0).
  description = "SQL Server engine version. Empty = RDS default for sqlserver-ex."
}

variable "master_username" {
  type        = string
  description = "Master (admin) username"
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Master (admin) password, generated by the dashboard at provision"
}

variable "db_subnet_group_name" {
  type        = string
  description = "DB subnet group placing the instance in private subnets"
}

variable "vpc_security_group_ids" {
  type        = list(string)
  default     = []
  description = "Security groups controlling access (Jumpoint/PRA reachability only)"
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (workgroup, managed-by)"
}

variable "parameter_group_name" {
  type    = string
  default = ""
  # Optional existing DB parameter group. The managed DB is reached ONLY through a
  # BeyondTrust PRA *protocol* tunnel (tunnel_type=mssql), which is a TDS-aware proxy
  # that negotiates encryption with the backend itself — so unlike PostgreSQL/MySQL,
  # SQL Server does NOT need forced-SSL disabled (RDS SQL Server's rds.force_ssl
  # defaults to 0/optional anyway). Empty = RDS default group. A sqlserver-ex-16.0
  # group with rds.force_ssl=0 may be attached as a belt-and-suspenders safety net.
  description = "Optional existing DB parameter group. Empty = RDS default (fine — the mssql tunnel handles TLS)."
}

# ── Resource — always private (no public endpoint) ──────────────────────────
# publicly_accessible = false is load-bearing: the only path in is the PRA
# protocol-tunnel jump (via the beyondtrust/sra provider). Never expose a public
# endpoint. NOTE: RDS for SQL Server does NOT accept `db_name` at creation (unlike
# PostgreSQL/MySQL) — you connect to the `master` system database and create app
# databases afterward — so this module intentionally omits db_name. sqlserver-ex
# (Express) is the cheapest edition and is always license-included.

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = "sqlserver-ex"
  engine_version = var.engine_version != "" ? var.engine_version : null
  instance_class = var.instance_class
  license_model  = "license-included"

  allocated_storage = var.allocated_storage
  username          = var.master_username
  password          = var.master_password

  publicly_accessible    = false
  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = var.vpc_security_group_ids
  parameter_group_name   = var.parameter_group_name != "" ? var.parameter_group_name : null

  skip_final_snapshot = true
  apply_immediately   = true
  deletion_protection = false

  tags = var.tags
}

# ── Outputs (match the module contract: instance_id / private_host / port) ────

output "instance_id" {
  value       = aws_db_instance.this.id
  description = "RDS instance identifier / resource id"
}

output "private_host" {
  value       = aws_db_instance.this.address
  description = "Private endpoint host — reached only via the PRA tunnel"
}

output "port" {
  value       = aws_db_instance.this.port
  description = "Database port (SQL Server: 1433)"
}
