terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 3.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "azurerm" {
  features {}
}

# ═══════════════════════════════════════════════════════════════════════════════
# Azure SQL Managed Instance — the Entitle-COMPATIBLE managed SQL Server on Azure.
#
# Unlike Azure SQL Database (terraform/db_azure_sqlserver), a Managed Instance is a
# near-full SQL Server: the deployment admin login is a member of the `sysadmin` fixed
# server role, so Entitle's Microsoft SQL Server connector can manage it (standard
# mode = sysadmin). Azure SQL Database is a logical server with no server-level grants,
# which is why db_azure_sqlserver is NOT Entitle-viable.
#
# SCAFFOLD (live provisioning DEFERRED — see docs/design/entitle-compatible-sqlserver.md):
#   * MI is VNet-injected into a subnet DELEGATED to Microsoft.Sql/managedInstances,
#     with a dedicated NSG + route table attached (Azure enforces specific rules). This
#     module expects that subnet to already exist (sandbox-created), mirroring how
#     db_azure_sqlserver expects its private-endpoint subnet — pass its id as subnet_id.
#     No Private Endpoint is needed (MI is natively private in the VNet).
#   * MI create is LONG (~hours) — well beyond the 5-10 min RDS-class apply the job
#     runner + progress milestones assume; long-apply handling is follow-on work.
# Always private (public_data_endpoint_enabled = false), reached via the PRA mssql tunnel.
# ═══════════════════════════════════════════════════════════════════════════════

# ── Variables ────────────────────────────────────────────────────────────────

variable "resource_group_name" {
  type        = string
  description = "Resource group the Managed Instance lands in"
}

variable "location" {
  type        = string
  description = "Azure region (e.g. eastus)"
}

variable "identifier" {
  type        = string
  description = "Managed Instance name (globally unique, lowercase letters/digits/hyphens)"
}

variable "administrator_login" {
  type        = string
  description = "MI admin login — a member of the sysadmin server role"
}

variable "administrator_password" {
  type        = string
  sensitive   = true
  description = "MI admin password, generated by the dashboard at provision"
}

variable "sku_name" {
  type        = string
  default     = "GP_Gen5"
  description = "MI SKU family (GP_Gen5 = General Purpose; BC_Gen5 = Business Critical)."
}

variable "vcores" {
  type        = number
  default     = 4
  description = "vCores (GP_Gen5 supports 4, 8, 16, …)."
}

variable "storage_size_in_gb" {
  type        = number
  default     = 32
  description = "Storage in GB (MI minimum is 32, in 32 GB increments)."
}

variable "subnet_id" {
  type = string
  # A subnet DELEGATED to Microsoft.Sql/managedInstances, with its own NSG + route
  # table (Azure-enforced). Sandbox-created; the dashboard maps azure_sqlmi_subnet_id
  # here. NOT the plain private-endpoint subnet the Azure SQL Database module uses.
  description = "Delegated subnet id (Microsoft.Sql/managedInstances) with NSG + route table."
}

variable "license_type" {
  type        = string
  default     = "BasePrice"
  description = "BasePrice (AHB — bring your own SQL licenses) or LicenseIncluded."
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (managed-by, clouddb-id)"
}

# ── Resource — always private (VNet-injected, no public data endpoint) ────────
# The MI is reachable only inside the VNet on its private FQDN; the PRA mssql tunnel
# on the jumpoint VM connects to it (tunnel_type=mssql, TDS-aware TLS to the backend).

resource "azurerm_mssql_managed_instance" "this" {
  name                = var.identifier
  resource_group_name = var.resource_group_name
  location            = var.location

  administrator_login          = var.administrator_login
  administrator_login_password = var.administrator_password

  license_type       = var.license_type
  sku_name           = var.sku_name
  vcores             = var.vcores
  storage_size_in_gb = var.storage_size_in_gb
  subnet_id          = var.subnet_id

  public_data_endpoint_enabled = false
  minimum_tls_version          = "1.2"

  tags = var.tags
}

# ── Outputs (match the module contract: instance_id / private_host / port) ────

output "instance_id" {
  value       = azurerm_mssql_managed_instance.this.id
  description = "Managed Instance resource id"
}

output "private_host" {
  value       = azurerm_mssql_managed_instance.this.fqdn
  description = "MI private FQDN — resolves to the VNet-internal IP"
}

output "port" {
  value       = 1433
  description = "Database port (SQL Server)"
}
