#!/usr/bin/env bash
# One-command onboarding for the Infrastructure Management Dashboard
# (Community Edition) on macOS and Linux.
#
# Mirrors scripts/Onboard-Dashboard.ps1 for Windows: preflight, .env
# bootstrap, secret auto-gen, `docker compose up`, health poll, browser open.
#
# Usage:
#   ./scripts/onboard.sh            # normal run
#   ./scripts/onboard.sh --build    # force image rebuild
#   ./scripts/onboard.sh --no-open  # skip opening the browser

set -euo pipefail

BUILD=0
NO_OPEN=0
for arg in "$@"; do
    case "$arg" in
        --build) BUILD=1 ;;
        --no-open) NO_OPEN=1 ;;
        -h|--help)
            sed -n '2,12p' "$0"
            exit 0
            ;;
        *) echo "unknown arg: $arg" >&2; exit 2 ;;
    esac
done

# Repo root is the parent of the directory holding this script.
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
ENV_FILE="$REPO_ROOT/.env"
ENV_EXAMPLE="$REPO_ROOT/.env.example"
COMPOSE_FILE="$REPO_ROOT/docker-compose.yml"
HEALTH_URL="http://localhost:8000/api/health"
DASHBOARD_URL="http://localhost:8000"

# ANSI color helpers (no-op when stdout is not a TTY).
if [[ -t 1 ]]; then
    C_STEP=$'\033[36m'; C_OK=$'\033[32m'; C_WARN=$'\033[33m'
    C_FAIL=$'\033[31m'; C_RESET=$'\033[0m'
else
    C_STEP=""; C_OK=""; C_WARN=""; C_FAIL=""; C_RESET=""
fi
step()  { printf "%s==>%s %s\n" "$C_STEP" "$C_RESET" "$1"; }
ok()    { printf "    %s%s%s\n" "$C_OK"   "$1" "$C_RESET"; }
warn()  { printf "    %s%s%s\n" "$C_WARN" "$1" "$C_RESET"; }
fail()  { printf "    %s%s%s\n" "$C_FAIL" "$1" "$C_RESET" >&2; }

# ── 1. Preflight ────────────────────────────────────────────────────────
step "Checking prerequisites"

for cmd in git docker curl; do
    if ! command -v "$cmd" >/dev/null 2>&1; then
        fail "'$cmd' not found on PATH."
        case "$cmd" in
            docker) fail "Install Docker Desktop: https://www.docker.com/products/docker-desktop/" ;;
            git)    fail "Install git (macOS: 'xcode-select --install'; Linux: use your package manager)" ;;
            curl)   fail "Install curl via your package manager." ;;
        esac
        exit 1
    fi
    ok "$cmd found"
done

if ! docker info --format '{{.ServerVersion}}' >/dev/null 2>&1; then
    fail "Docker daemon is not responding. Is Docker Desktop running?"
    fail "Start Docker Desktop, wait for the whale icon to settle, then rerun."
    exit 1
fi
ok "Docker daemon responding"

if [[ ! -f "$COMPOSE_FILE" ]]; then
    fail "docker-compose.yml not found at $COMPOSE_FILE."
    fail "Run this script from a clone of the dashboard repository."
    exit 1
fi

# ── 2. Bootstrap .env ───────────────────────────────────────────────────
step "Checking .env"

if [[ ! -f "$ENV_FILE" ]]; then
    if [[ ! -f "$ENV_EXAMPLE" ]]; then
        fail ".env.example is missing from the repo — cannot bootstrap .env."
        exit 1
    fi
    cp "$ENV_EXAMPLE" "$ENV_FILE"
    ok "Created .env from .env.example"
    echo
    warn "───────────────────────────────────────────────────────────────────"
    warn " First-run setup: fill in the REPLACE_ME values in .env and rerun."
    warn "   Required sections: AWS + Azure (core app + secrets are auto-"
    warn "   generated by this script)."
    warn " Opening \$EDITOR (or nano) on .env..."
    warn "───────────────────────────────────────────────────────────────────"
    echo
    "${EDITOR:-nano}" "$ENV_FILE" || true
    exit 0
fi
ok ".env exists"

# Read a value from .env (ignores comments and blanks). Empty if unset.
read_env() {
    local key="$1"
    awk -F= -v k="$key" '
        /^[[:space:]]*#/ { next }
        /^[[:space:]]*$/ { next }
        $1 == k { sub(/^[^=]*=/, ""); print; exit }
    ' "$ENV_FILE"
}

# Replace or append KEY=VALUE in .env. Uses a temp file + mv for atomicity.
set_env() {
    local key="$1" value="$2"
    local tmp; tmp="$(mktemp)"
    awk -F= -v k="$key" -v v="$value" '
        BEGIN { done = 0 }
        $1 == k && !/^[[:space:]]*#/ { print k "=" v; done = 1; next }
        { print }
        END { if (!done) print k "=" v }
    ' "$ENV_FILE" > "$tmp"
    mv "$tmp" "$ENV_FILE"
}

new_hex() {
    # $1 = number of bytes. Falls back to /dev/urandom if openssl missing.
    if command -v openssl >/dev/null 2>&1; then
        openssl rand -hex "$1"
    else
        head -c "$1" /dev/urandom | od -An -tx1 | tr -d ' \n'
    fi
}

# ── 3. Auto-generate secrets still at placeholder values ────────────────
step "Auto-generating secrets at placeholder values"

changed=0
if [[ "$(read_env JWT_SECRET_KEY)" == "REPLACE_ME_WITH_32_BYTE_HEX" || -z "$(read_env JWT_SECRET_KEY)" ]]; then
    set_env JWT_SECRET_KEY "$(new_hex 32)"; ok "Generated JWT_SECRET_KEY"; changed=1
fi
if [[ "$(read_env POSTGRES_PASSWORD)" == "REPLACE_ME_WITH_STRONG_PASSWORD" || -z "$(read_env POSTGRES_PASSWORD)" ]]; then
    set_env POSTGRES_PASSWORD "$(new_hex 16)"; ok "Generated POSTGRES_PASSWORD"; changed=1
fi
if [[ "$(read_env FIRST_RUN_ADMIN_PASSWORD)" == "REPLACE_ME_WITH_ADMIN_PASSWORD" || -z "$(read_env FIRST_RUN_ADMIN_PASSWORD)" ]]; then
    set_env FIRST_RUN_ADMIN_PASSWORD "$(new_hex 12)"; ok "Generated FIRST_RUN_ADMIN_PASSWORD"; changed=1
fi
(( changed )) || ok "All auto-generated secrets already set"

# ── 4. Validate no REPLACE_ME_* remain ──────────────────────────────────
step "Validating .env values"

bad_keys=$(grep -E '^[^#=]+=REPLACE_ME_' "$ENV_FILE" | cut -d= -f1 || true)
if [[ -n "$bad_keys" ]]; then
    echo
    fail "The following values still need to be filled in:"
    while IFS= read -r k; do printf "      - %s\n" "$k" >&2; done <<< "$bad_keys"
    echo
    warn "See docs/ONBOARDING.md for instructions on obtaining AWS and"
    warn "Azure credentials. Opening \$EDITOR on .env..."
    "${EDITOR:-nano}" "$ENV_FILE" || true
    exit 1
fi
ok "No REPLACE_ME placeholders remain"

# ── 5. Bring up the stack ───────────────────────────────────────────────
step "Starting Docker Compose stack"

compose_args=(compose -f "$COMPOSE_FILE" up -d)
(( BUILD )) && compose_args+=(--build)

if ! docker "${compose_args[@]}"; then
    fail "docker compose up failed."
    fail "Recent logs:"
    docker compose -f "$COMPOSE_FILE" logs --tail 50 app || true
    exit 1
fi
ok "Containers started"

# ── 6. Wait for health endpoint ─────────────────────────────────────────
step "Waiting for health endpoint ($HEALTH_URL)"

ready=0
for i in $(seq 1 90); do
    sleep 1
    if curl -fsS -o /dev/null --max-time 2 "$HEALTH_URL"; then
        ready=1
        ok "Healthy after ${i}s"
        break
    fi
done

if ! (( ready )); then
    fail "Health endpoint did not respond within 90 seconds."
    fail "Recent app logs:"
    docker compose -f "$COMPOSE_FILE" logs --tail 50 app || true
    echo
    warn "Common causes:"
    warn "  - Invalid AWS or Azure credentials (app crashes at startup)"
    warn "  - Port 8000 already in use by another process"
    warn "  - Database container still initializing — try rerunning in ~30s"
    exit 1
fi

# ── 7. Open the browser ─────────────────────────────────────────────────
echo
ok "Dashboard is up at $DASHBOARD_URL"
if ! (( NO_OPEN )); then
    if command -v open >/dev/null 2>&1; then
        open "$DASHBOARD_URL" || true           # macOS
    elif command -v xdg-open >/dev/null 2>&1; then
        xdg-open "$DASHBOARD_URL" >/dev/null 2>&1 || true  # Linux
    fi
fi

echo
printf "%sNext steps:%s\n" "$C_STEP" "$C_RESET"
admin_user=$(read_env FIRST_RUN_ADMIN_USERNAME)
[[ -z "$admin_user" ]] && admin_user=admin
echo "  - Log in with username '$admin_user' — password is in .env as FIRST_RUN_ADMIN_PASSWORD"
echo "    (Change it via Settings after first login; the env var is ignored once users exist.)"
echo "  - See docs/ONBOARDING.md for the feature-test checklist"
echo "  - Stop the stack with:  docker compose -f docker-compose.yml down"
