<#
.SYNOPSIS
    One-command onboarding for the Infrastructure Management Dashboard
    (Community Edition) on Windows.

.DESCRIPTION
    Runs preflight checks, bootstraps .env from .env.example on first run,
    fills in auto-generatable secrets, brings up the docker-compose stack,
    waits for the health endpoint, and opens the dashboard in the browser.

    Re-running is safe: preflight is idempotent and the compose stack
    reconciles to the current image / config.

.PARAMETER Build
    Force a Docker image rebuild before starting.

.PARAMETER Hub
    Run the prebuilt image from Docker Hub (chrweav/infra-dashboard) using
    docker-compose.hub.yml instead of building from source. Mutually
    exclusive with -Build.

.PARAMETER NoBrowser
    Skip opening the browser when the stack comes up.

.EXAMPLE
    .\scripts\Onboard-Dashboard.ps1

.EXAMPLE
    .\scripts\Onboard-Dashboard.ps1 -Hub

.EXAMPLE
    .\scripts\Onboard-Dashboard.ps1 -Build

.NOTES
    Prerequisites (one-time, document these in docs/ONBOARDING.md):
      - Docker Desktop installed and running
      - PowerShell 7+ (pwsh)
      - git
#>
[CmdletBinding()]
param(
    [switch]$Build,
    [switch]$Hub,
    [switch]$NoBrowser
)

$ErrorActionPreference = "Stop"
$PSNativeCommandUseErrorActionPreference = $true

if ($Hub -and $Build) {
    [Console]::Error.WriteLine("error: -Hub (run the prebuilt Docker Hub image) and -Build (build from source) are mutually exclusive.")
    exit 2
}

# Resolve the repo root as the parent of the scripts\ directory this file lives in.
$repoRoot    = Split-Path -Parent $PSScriptRoot
$envFile     = Join-Path $repoRoot ".env"
$envExample  = Join-Path $repoRoot ".env.example"
$composeFile = if ($Hub) { Join-Path $repoRoot "docker-compose.hub.yml" } else { Join-Path $repoRoot "docker-compose.yml" }
$healthUrl   = "http://localhost:8001/api/health"
$dashboardUrl = "http://localhost:8001"

function Write-Step   { param([string]$m) Write-Host "==>" $m -ForegroundColor Cyan }
function Write-Ok     { param([string]$m) Write-Host "   " $m -ForegroundColor Green }
function Write-Warn   { param([string]$m) Write-Host "   " $m -ForegroundColor Yellow }
function Write-Fail   { param([string]$m) Write-Host "   " $m -ForegroundColor Red }

function Test-CommandExists {
    param([string]$Name)
    $null -ne (Get-Command $Name -ErrorAction SilentlyContinue)
}

# ── 1. Preflight: required tools ───────────────────────────────────────
Write-Step "Checking prerequisites"

if ($PSVersionTable.PSVersion.Major -lt 7) {
    Write-Fail "PowerShell 7+ is required. You are running $($PSVersionTable.PSVersion)."
    Write-Fail "Install from https://aka.ms/powershell and rerun with 'pwsh'."
    exit 1
}
Write-Ok "PowerShell $($PSVersionTable.PSVersion)"

foreach ($cmd in @("git", "docker")) {
    if (-not (Test-CommandExists $cmd)) {
        Write-Fail "'$cmd' not found on PATH."
        if ($cmd -eq "docker") {
            Write-Fail "Install Docker Desktop from https://www.docker.com/products/docker-desktop/"
        } elseif ($cmd -eq "git") {
            Write-Fail "Install git from https://git-scm.com/download/win"
        }
        exit 1
    }
    Write-Ok "$cmd found"
}

# Docker Desktop must be running for `docker info` to succeed.
try {
    docker info --format "{{.ServerVersion}}" 2>&1 | Out-Null
    if ($LASTEXITCODE -ne 0) { throw "docker info failed" }
} catch {
    Write-Fail "Docker daemon is not responding. Is Docker Desktop running?"
    Write-Fail "Start Docker Desktop, wait for the whale icon to settle, then rerun."
    exit 1
}
Write-Ok "Docker daemon responding"

if (-not (Test-Path $composeFile)) {
    Write-Fail "$(Split-Path -Leaf $composeFile) not found at $composeFile."
    Write-Fail "Run this script from a clone of the dashboard repository."
    exit 1
}

# ── 2. Bootstrap .env ──────────────────────────────────────────────────
Write-Step "Checking .env"

if (-not (Test-Path $envFile)) {
    if (-not (Test-Path $envExample)) {
        Write-Fail ".env.example is missing from the repo — cannot bootstrap .env."
        exit 1
    }
    Copy-Item $envExample $envFile
    Write-Ok "Created .env from .env.example"
    Write-Host ""
    Write-Warn "───────────────────────────────────────────────────────────────────"
    Write-Warn " First-run setup: fill in the REPLACE_ME values in .env and rerun."
    Write-Warn "   Required sections: AWS + Azure (core app + secrets are auto-"
    Write-Warn "   generated by this script)."
    Write-Warn " Opening .env in Notepad..."
    Write-Warn "───────────────────────────────────────────────────────────────────"
    Write-Host ""
    Start-Process -FilePath notepad.exe -ArgumentList $envFile -Wait:$false
    exit 0
}
Write-Ok ".env exists"

# Parse .env into a hashtable (ignores blank lines and comments).
function Read-EnvFile {
    param([string]$Path)
    $out = [ordered]@{}
    foreach ($line in Get-Content -LiteralPath $Path) {
        $trim = $line.Trim()
        if (-not $trim -or $trim.StartsWith("#")) { continue }
        $eq = $trim.IndexOf("=")
        if ($eq -lt 1) { continue }
        $k = $trim.Substring(0, $eq).Trim()
        $v = $trim.Substring($eq + 1).Trim()
        $out[$k] = $v
    }
    return $out
}

function Set-EnvValue {
    param([string]$Path, [string]$Key, [string]$Value)
    $lines = Get-Content -LiteralPath $Path
    $pattern = "^\s*$([regex]::Escape($Key))\s*="
    $replaced = $false
    $newLines = foreach ($line in $lines) {
        if ($line -match $pattern) {
            "$Key=$Value"
            $replaced = $true
        } else {
            $line
        }
    }
    if (-not $replaced) { $newLines += "$Key=$Value" }
    Set-Content -LiteralPath $Path -Value $newLines -Encoding UTF8
}

function New-HexSecret {
    param([int]$Bytes = 32)
    $b = New-Object byte[] $Bytes
    [System.Security.Cryptography.RandomNumberGenerator]::Fill($b)
    return ([System.BitConverter]::ToString($b) -replace "-", "").ToLowerInvariant()
}

# ── 3. Generate JWT secret key file ────────────────────────────────────
# The JWT key is the root of trust for DB-encrypted integration credentials.
# It lives in .jwt_secret_key (Docker secret mount) rather than .env so
# the rest of .env is safe to inspect or share for debugging.
Write-Step "Checking JWT secret key"

$jwtKeyFile = Join-Path $repoRoot ".jwt_secret_key"
if (-not (Test-Path $jwtKeyFile)) {
    New-HexSecret -Bytes 32 | Set-Content -LiteralPath $jwtKeyFile -Encoding ASCII -NoNewline

    # Restrict to current user only (equivalent of chmod 600).
    $acl = Get-Acl -LiteralPath $jwtKeyFile
    $acl.SetAccessRuleProtection($true, $false)
    $me = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
    $rule = New-Object System.Security.AccessControl.FileSystemAccessRule(
        $me, "FullControl", "Allow"
    )
    $acl.SetAccessRule($rule)
    Set-Acl -LiteralPath $jwtKeyFile -AclObject $acl

    Write-Ok "Generated .jwt_secret_key (owner-only permissions)"
} else {
    Write-Ok ".jwt_secret_key already exists"
}

# ── 4. Auto-generate remaining bootstrap secrets ────────────────────────
Write-Step "Auto-generating secrets at placeholder values"

$envVars = Read-EnvFile -Path $envFile
$changed = $false

if ($envVars.POSTGRES_PASSWORD -eq "REPLACE_ME_WITH_STRONG_PASSWORD" -or
    -not $envVars.POSTGRES_PASSWORD) {
    Set-EnvValue -Path $envFile -Key "POSTGRES_PASSWORD" -Value (New-HexSecret -Bytes 16)
    Write-Ok "Generated POSTGRES_PASSWORD"
    $changed = $true
}

if ($envVars.FIRST_RUN_ADMIN_PASSWORD -eq "REPLACE_ME_WITH_ADMIN_PASSWORD" -or
    -not $envVars.FIRST_RUN_ADMIN_PASSWORD) {
    Set-EnvValue -Path $envFile -Key "FIRST_RUN_ADMIN_PASSWORD" -Value (New-HexSecret -Bytes 12)
    Write-Ok "Generated FIRST_RUN_ADMIN_PASSWORD"
    $changed = $true
}

if (-not $changed) { Write-Ok "All auto-generated secrets already set" }

# ── 4b. Set the default job-worker count ───────────────────────────────
# Long jobs run one-per-worker, so the replica count is how many run concurrently.
# Default to 3. Migrate installs still on the old default of 1, but leave any other
# explicit choice (2, 5, ...) untouched.
Write-Step "Setting job-worker default"
$workerReplicas = $envVars.WORKER_REPLICAS
if (-not $workerReplicas -or $workerReplicas -eq "1") {
    Set-EnvValue -Path $envFile -Key "WORKER_REPLICAS" -Value "3"
    Write-Ok "Set WORKER_REPLICAS=3 (default job-worker count)"
} else {
    Write-Ok "WORKER_REPLICAS=$workerReplicas (keeping explicit value)"
}

# Re-read after generation so validation sees the new values.
$envVars = Read-EnvFile -Path $envFile

# ── 4. Validate REPLACE_ME placeholders are filled in ──────────────────
Write-Step "Validating .env values"

$placeholders = @()
foreach ($k in $envVars.Keys) {
    $v = $envVars[$k]
    if ($v -like "REPLACE_ME_*") {
        $placeholders += $k
    }
}

if ($placeholders.Count -gt 0) {
    Write-Host ""
    Write-Fail "The following values still need to be filled in:"
    foreach ($k in $placeholders) {
        Write-Host "      - $k" -ForegroundColor Red
    }
    Write-Host ""
    Write-Warn "See docs/ONBOARDING.md for instructions on obtaining AWS and"
    Write-Warn "Azure credentials. Opening .env in Notepad..."
    Start-Process -FilePath notepad.exe -ArgumentList $envFile -Wait:$false
    exit 1
}
Write-Ok "No REPLACE_ME placeholders remain"

# ── 5. Bring up the stack ──────────────────────────────────────────────
if ($Hub) {
    Write-Step "Pulling prebuilt image and starting Docker Compose stack"
    # Pull the latest published image first so reruns pick up new releases
    # (compose only auto-pulls when the image is absent locally).
    & docker compose -f $composeFile pull
    if ($LASTEXITCODE -ne 0) {
        Write-Fail "docker compose pull failed - could not fetch the prebuilt image."
        Write-Fail "Behind a TLS-inspecting proxy, ensure Docker trusts your corp CA for Docker Hub"
        Write-Fail "(see docs/ONBOARDING.md: 'docker pull fails with a certificate error')."
        exit $LASTEXITCODE
    }
} else {
    Write-Step "Starting Docker Compose stack"
}

$composeArgs = @("compose", "-f", $composeFile, "up", "-d")
if ($Build) { $composeArgs += "--build" }

& docker @composeArgs
if ($LASTEXITCODE -ne 0) {
    Write-Fail "docker compose up failed (exit $LASTEXITCODE)."
    Write-Fail "Recent logs:"
    & docker compose -f $composeFile logs --tail 50 app
    exit $LASTEXITCODE
}
Write-Ok "Containers started"

# ── 6. Wait for health endpoint ────────────────────────────────────────
Write-Step "Waiting for health endpoint ($healthUrl)"

$ready = $false
for ($i = 1; $i -le 90; $i++) {
    Start-Sleep -Seconds 1
    try {
        $resp = Invoke-WebRequest -Uri $healthUrl -UseBasicParsing `
            -TimeoutSec 2 -ErrorAction Stop
        if ($resp.StatusCode -eq 200) {
            $ready = $true
            Write-Ok "Healthy after ${i}s"
            break
        }
    } catch { }
}

if (-not $ready) {
    Write-Fail "Health endpoint did not respond within 90 seconds."
    Write-Fail "Recent app logs:"
    & docker compose -f $composeFile logs --tail 50 app
    Write-Host ""
    Write-Warn "Common causes:"
    Write-Warn "  - Invalid AWS or Azure credentials (app crashes at startup)"
    Write-Warn "  - Port 8001 already in use by another process"
    Write-Warn "  - Database container still initializing — try rerunning in ~30s"
    exit 1
}

# ── 7. Open the browser ────────────────────────────────────────────────
Write-Host ""
Write-Ok "Dashboard is up at $dashboardUrl"
if (-not $NoBrowser) {
    Start-Process $dashboardUrl
}

Write-Host ""
Write-Host "Next steps:" -ForegroundColor Cyan
$adminUser = $envVars.FIRST_RUN_ADMIN_USERNAME
if (-not $adminUser) { $adminUser = "admin" }
Write-Host "  - Log in with username '$adminUser' — password is in .env as FIRST_RUN_ADMIN_PASSWORD"
Write-Host "    (Change it via Settings after first login; the env var is ignored once users exist.)"
Write-Host "  - See docs/ONBOARDING.md for the feature-test checklist"
Write-Host "  - Stop the stack with:  docker compose -f $(Split-Path -Leaf $composeFile) down"
