terraform {
  required_providers {
    google = {
      source  = "hashicorp/google"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "google" {
  project = var.project
  region  = var.region
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "project" {
  type        = string
  description = "GCP project id for the Cloud SQL instance"
}

variable "region" {
  type        = string
  description = "GCP region for the Cloud SQL instance"
}

variable "identifier" {
  type        = string
  description = "Cloud SQL instance name (unique per project; cannot be reused for ~1 week after delete)"
}

variable "tier" {
  type    = string
  default = "db-custom-2-7680"
  # SQL Server on Cloud SQL does NOT support shared-core tiers (db-f1-micro / db-g1-small);
  # it requires a dedicated-core custom tier. db-custom-2-7680 (2 vCPU / 7.5 GiB) is a safe
  # default; db-custom-1-3840 is the smallest SQL Server allows.
  description = "Cloud SQL machine tier. SQL Server needs a db-custom-* tier (no shared-core)."
}

variable "disk_size" {
  type        = number
  default     = 20
  description = "Data disk size in GiB"
}

variable "database_version" {
  type        = string
  default     = "SQLSERVER_2022_STANDARD"
  description = "Cloud SQL SQL Server version (e.g. SQLSERVER_2022_STANDARD / _EXPRESS / _WEB / _ENTERPRISE)."
}

variable "db_name" {
  type        = string
  description = "Initial database name (created on the instance via google_sql_database)"
}

variable "master_username" {
  type    = string
  default = "sqlserver"
  # Cloud SQL for SQL Server's admin login is the built-in `sqlserver` account, whose
  # password is the instance root_password (below) — you cannot rename it. This variable
  # exists for interface parity (the dashboard passes it to the PRA tunnel as the
  # connection username); Cloud SQL ignores the name. Leave it "sqlserver".
  description = "Admin login (always 'sqlserver' on Cloud SQL SQL Server; used by the PRA tunnel)."
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Admin (sqlserver) password — set as the instance root_password; generated by the dashboard at provision"
}

variable "private_network" {
  type        = string
  description = "VPC the instance gets its private IP on — a bare network name (e.g. my-vpc) or a full self-link/path. Private services access must already be configured on it (the sandbox does this)."
}

variable "ssl_mode" {
  type    = string
  default = "ALLOW_UNENCRYPTED_AND_ENCRYPTED"
  # The managed DB is reached ONLY through a BeyondTrust PRA *protocol* tunnel
  # (tunnel_type=mssql), a TDS-aware proxy that negotiates its own encryption with the
  # backend. Unlike Postgres/MySQL this isn't strictly required, but
  # ALLOW_UNENCRYPTED_AND_ENCRYPTED keeps the cleartext path open as a safety net.
  description = "Cloud SQL ssl_mode. ALLOW_UNENCRYPTED_AND_ENCRYPTED keeps the cleartext path open for the tunnel."
}

variable "labels" {
  type        = map(string)
  default     = {}
  description = "Resource labels (managed-by, clouddb-id). Keys/values must be lowercase."
}

locals {
  # google_sql_database_instance.private_network needs a fully-qualified network
  # self-link (projects/<project>/global/networks/<name>), not a bare name. If the
  # caller passed a path/URL (contains "/") use it as-is; otherwise qualify the bare
  # name (the common sandbox config) with this module's project.
  private_network_id = can(regex("/", var.private_network)) ? var.private_network : "projects/${var.project}/global/networks/${var.private_network}"

  # Every Cloud SQL SQL Server instance ships with these built-in system databases.
  # Asking google_sql_database to CREATE one fails ("database exists") and aborts the
  # apply. When db_name collides with a built-in, skip creating it — the database
  # already exists (and the PRA tunnel targets `master` regardless).
  reserved_db_names = ["master", "model", "msdb", "tempdb"]
  create_database   = !contains(local.reserved_db_names, lower(var.db_name))
}

# ── Resource — always private (no public IP) ─────────────────────────────────
# ipv4_enabled = false is load-bearing: the only path in is the PRA protocol-tunnel
# jump (via the beyondtrust/sra provider). Never enable a public IP. The admin login is
# the built-in `sqlserver` account — its password is the instance root_password (Cloud
# SQL SQL Server has no google_sql_user for the admin, unlike postgres/mysql).

resource "google_sql_database_instance" "this" {
  name                = var.identifier
  project             = var.project
  region              = var.region
  database_version    = var.database_version
  root_password       = var.master_password
  deletion_protection = false

  settings {
    tier              = var.tier
    disk_size         = var.disk_size
    availability_type = "ZONAL"
    user_labels       = var.labels

    ip_configuration {
      ipv4_enabled    = false
      private_network = local.private_network_id
      ssl_mode        = var.ssl_mode
    }

    backup_configuration {
      enabled = false
    }
  }
}

resource "google_sql_database" "this" {
  count    = local.create_database ? 1 : 0
  name     = var.db_name
  project  = var.project
  instance = google_sql_database_instance.this.name
}

# NOTE: no google_sql_user — the admin is the built-in `sqlserver` login set via
# root_password above (the PRA tunnel injects that credential; it connects to `master`).

# ── Outputs (match the module contract: instance_id / private_host / port) ────

output "instance_id" {
  value       = google_sql_database_instance.this.name
  description = "Cloud SQL instance name / resource id"
}

output "private_host" {
  value       = google_sql_database_instance.this.private_ip_address
  description = "Private IP — reached only via the PRA tunnel"
}

output "port" {
  value       = 1433
  description = "Database port (SQL Server)"
}
