terraform {
  required_providers {
    google = {
      source = "hashicorp/google"
      # Cloud SQL MySQL 8.4 — whose user is created on caching_sha2_password (required
      # by the PRA MySQL tunnel; MYSQL_8_0 uses mysql_native_password, which PRA rejects)
      # — is a valid database_version only from google provider 6.x (added Dec 2024). The
      # 5.x line predates it. Scoped to THIS module; db_gcp_postgres stays on ~> 5.0
      # (separate root modules each resolve their own provider).
      version = "~> 6.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "google" {
  project = var.project
  region  = var.region
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "project" {
  type        = string
  description = "GCP project id for the Cloud SQL instance"
}

variable "region" {
  type        = string
  description = "GCP region for the Cloud SQL instance"
}

variable "identifier" {
  type        = string
  description = "Cloud SQL instance name (unique per project; cannot be reused for ~1 week after delete)"
}

variable "tier" {
  type        = string
  default     = "db-f1-micro"
  description = "Cloud SQL machine tier (e.g. db-f1-micro, db-g1-small, db-custom-1-3840)"
}

variable "edition" {
  type    = string
  default = "ENTERPRISE"
  # MYSQL_8_4 defaults to the ENTERPRISE_PLUS edition, which does NOT offer shared-core
  # tiers like db-f1-micro. Pinning ENTERPRISE keeps the cheap default tier valid on 8.4.
  description = "Cloud SQL edition. ENTERPRISE keeps shared-core tiers (db-f1-micro) available on MYSQL_8_4."
}

variable "disk_size" {
  type        = number
  default     = 20
  description = "Data disk size in GiB"
}

variable "database_version" {
  type    = string
  default = "MYSQL_8_4"
  # Must be MYSQL_8_4, not MYSQL_8_0: Cloud SQL creates the user on mysql_native_password
  # at 8.0 (Google's deliberate default for client compatibility), which the PRA MySQL
  # tunnel rejects ("Unsupported plugin offered from server: mysql_native_password --
  # reconfigure server for caching_sha2_password"). 8.4 drops mysql_native_password as a
  # default, so the user is born on caching_sha2_password. (AWS analog: RDS MySQL 8.4;
  # Azure analog: Flexible Server 8.4.) MYSQL_8_4 needs google provider >= 6.x.
  description = "Cloud SQL MySQL version (MYSQL_8_4 — required so the admin uses caching_sha2_password)"
}

variable "db_name" {
  type        = string
  description = "Initial database name"
}

variable "master_username" {
  type        = string
  description = "Master (admin) username"
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Master (admin) password, generated by the dashboard at provision"
}

variable "private_network" {
  type        = string
  description = "VPC the instance gets its private IP on — a bare network name (e.g. my-vpc) or a full self-link/path. Private services access must already be configured on it (the sandbox does this)."
}

variable "ssl_mode" {
  type    = string
  default = "ALLOW_UNENCRYPTED_AND_ENCRYPTED"
  # The managed DB is reached ONLY through a BeyondTrust PRA *protocol* tunnel, which
  # proxies the cleartext MySQL wire protocol (that is how it injects the Vault credential
  # and records the session) — the sra_my_sql_tunnel_jump has no backend-TLS option. Cloud
  # SQL defaults to requiring SSL, which rejects the tunnel's cleartext jumpoint→DB
  # connection. ALLOW_UNENCRYPTED_AND_ENCRYPTED permits it. The client→jumpoint hop is
  # still PRA-encrypted, so only the intra-VPC jumpoint→DB hop is cleartext.
  description = "Cloud SQL ssl_mode. ALLOW_UNENCRYPTED_AND_ENCRYPTED lets the PRA tunnel connect cleartext."
}

variable "labels" {
  type        = map(string)
  default     = {}
  description = "Resource labels (managed-by, clouddb-id). Keys/values must be lowercase."
}

locals {
  # google_sql_database_instance.private_network needs a fully-qualified network
  # self-link (projects/<project>/global/networks/<name>), not a bare name. If
  # the caller already passed a path/URL (contains "/"), use it as-is; otherwise
  # qualify the bare name (the common sandbox config) with this module's project.
  private_network_id = can(regex("/", var.private_network)) ? var.private_network : "projects/${var.project}/global/networks/${var.private_network}"
}

# ── Resource — always private (no public IP) ─────────────────────────────────
# ipv4_enabled = false is load-bearing: the only path in is the PRA protocol-
# tunnel jump (via the beyondtrust/sra provider). Never enable a public IP.

resource "google_sql_database_instance" "this" {
  name                = var.identifier
  project             = var.project
  region              = var.region
  database_version    = var.database_version
  deletion_protection = false

  settings {
    tier              = var.tier
    edition           = var.edition
    disk_size         = var.disk_size
    availability_type = "ZONAL"
    user_labels       = var.labels

    ip_configuration {
      ipv4_enabled    = false
      private_network = local.private_network_id
      ssl_mode        = var.ssl_mode
    }

    backup_configuration {
      enabled = false
    }
  }
}

resource "google_sql_database" "this" {
  name     = var.db_name
  project  = var.project
  instance = google_sql_database_instance.this.name
}

resource "google_sql_user" "master" {
  name     = var.master_username
  project  = var.project
  instance = google_sql_database_instance.this.name
  password = var.master_password
}

# ── Outputs (match the AWS module contract: instance_id / private_host / port) ─

output "instance_id" {
  value       = google_sql_database_instance.this.name
  description = "Cloud SQL instance name / resource id"
}

output "private_host" {
  value       = google_sql_database_instance.this.private_ip_address
  description = "Private IP — reached only via the PRA tunnel"
}

output "port" {
  value       = 3306
  description = "Database port (MySQL)"
}
