terraform {
  required_providers {
    mongodbatlas = {
      source  = "mongodb/mongodbatlas"
      version = "~> 2.19"
    }
  }
  required_version = ">= 1.3.0"
}

# Service-account auth (MongoDB's recommended method). The dashboard passes the
# client id/secret as MONGODB_ATLAS_CLIENT_ID / MONGODB_ATLAS_CLIENT_SECRET in the
# terraform subprocess environment — never as -vars, so they are never persisted
# with the job's variable set.
provider "mongodbatlas" {}

# ── Variables ────────────────────────────────────────────────────────────────

variable "org_id" {
  type        = string
  description = "Atlas organization the per-cluster project is created in"
}

variable "identifier" {
  type        = string
  description = "Name for both the Atlas project and the cluster (clouddb-<id8>)"
}

variable "tier" {
  type        = string
  default     = "FLEX"
  description = "FLEX (shared, public endpoint only) or a dedicated size (M10, M20, ...)"

  validation {
    condition     = upper(var.tier) == "FLEX" || can(regex("^M[1-9][0-9]*$", upper(var.tier)))
    error_message = "tier must be FLEX or a dedicated instance size such as M10."
  }
}

variable "backing_provider" {
  type        = string
  description = "Cloud the cluster runs on: AWS, AZURE or GCP (the PRA gateway's cloud)"

  validation {
    condition     = contains(["AWS", "AZURE", "GCP"], var.backing_provider)
    error_message = "backing_provider must be AWS, AZURE or GCP."
  }
}

variable "atlas_region" {
  type        = string
  description = "Atlas region name, e.g. US_EAST_1 (AWS), US_EAST_2 (Azure), CENTRAL_US (GCP)"
}

variable "master_username" {
  type        = string
  description = "Admin database user (authenticates against the admin database)"
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Admin database user's password, generated by the dashboard at provision"
}

variable "access_cidrs" {
  type        = list(string)
  default     = []
  description = "Project IP access list: the PRA gateway's egress /32, plus any extras (e.g. Entitle's IPs)"
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Tags on the project and the cluster (managed-by, clouddb-id)"
}

locals {
  is_flex = upper(var.tier) == "FLEX"
}

# ── Resources ────────────────────────────────────────────────────────────────
# One Atlas PROJECT per cluster, on purpose. The IP access list and database users
# are project-scoped, not cluster-scoped: two clusters sharing a project would share
# the gateway's access-list entry, and destroying either would cut the other off.
# A project of its own makes every entry here this cluster's alone, lets destroy
# remove all of it, and gives Entitle's Atlas integration a per-cluster project_id
# scope. Projects are free.

resource "mongodbatlas_project" "this" {
  name                         = var.identifier
  org_id                       = var.org_id
  with_default_alerts_settings = false
  tags                         = var.tags
}

# The endpoint is PUBLIC (Flex has no private endpoint) and locked to these CIDRs —
# normally the one /32 the PRA gateway egresses from, so the tunnel is still the only
# way a user reaches it. TLS and the database user's auth apply on top.
resource "mongodbatlas_project_ip_access_list" "this" {
  for_each   = toset(var.access_cidrs)
  project_id = mongodbatlas_project.this.id
  cidr_block = each.value
  comment    = "vm-dashboard ${var.identifier}"
}

resource "mongodbatlas_advanced_cluster" "this" {
  project_id   = mongodbatlas_project.this.id
  name         = var.identifier
  cluster_type = "REPLICASET"

  replication_specs = [
    {
      region_configs = [
        {
          # Flex: provider_name is the literal FLEX and the cloud goes in
          # backing_provider_name. Dedicated: provider_name IS the cloud and the size
          # lives in electable_specs. Both shapes carry every key (null where unused)
          # because the two arms of a conditional must have the same object type.
          provider_name         = local.is_flex ? "FLEX" : var.backing_provider
          backing_provider_name = local.is_flex ? var.backing_provider : null
          region_name           = var.atlas_region
          priority              = 7
          electable_specs = local.is_flex ? null : {
            instance_size = upper(var.tier)
            node_count    = 3
          }
        }
      ]
    }
  ]

  termination_protection_enabled = false
  tags                           = var.tags

  timeouts = {
    create = "60m"
    delete = "60m"
  }
}

resource "mongodbatlas_database_user" "admin" {
  project_id         = mongodbatlas_project.this.id
  username           = var.master_username
  password           = var.master_password
  auth_database_name = "admin"

  roles {
    role_name     = "atlasAdmin"
    database_name = "admin"
  }

  scopes {
    name = mongodbatlas_advanced_cluster.this.name
    type = "CLUSTER"
  }
}

# ── Outputs ─────────────────────────────────────────────────────────────────

locals {
  standard = mongodbatlas_advanced_cluster.this.connection_strings.standard
}

output "instance_id" {
  value       = mongodbatlas_advanced_cluster.this.cluster_id
  description = "Atlas cluster id"
}

output "project_id" {
  value       = mongodbatlas_project.this.id
  description = "The cluster's own Atlas project (Entitle's project_id scope)"
}

# The FIRST replica-set member of the mongodb:// seed list. A raw tcp PRA tunnel
# reaches exactly one host, so a client must connect with directConnection=true; on
# a dedicated cluster that member may be a secondary (reads need
# readPreference=secondaryPreferred). PRA 26.3's MongoDB tunnel lifts this.
output "private_host" {
  value       = regex("^mongodb://([^:/,]+)", local.standard)[0]
  description = "First replica-set member host — the PRA tcp tunnel target"
}

output "port" {
  value       = 27017
  description = "MongoDB port"
}

output "srv" {
  value       = mongodbatlas_advanced_cluster.this.connection_strings.standard_srv
  description = "mongodb+srv:// string (for clients that reach Atlas directly)"
}
