terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.0"
    }
  }
  required_version = ">= 1.3.0"
}

provider "aws" {
  region = var.region
}

# ── Variables ────────────────────────────────────────────────────────────────

variable "region" {
  type        = string
  description = "AWS region for the RDS instance"
}

variable "identifier" {
  type        = string
  description = "RDS instance identifier (unique per region)"
}

variable "engine" {
  type    = string
  default = "oracle-se2-cdb"
  # The container-database architecture, single-tenant: RDS creates one PDB named
  # db_name inside a CDB it names RDSCDB, and the master user lives in that PDB.
  # Not cosmetic — Entitle's Oracle connector manages pluggable databases ONLY, so a
  # non-CDB "oracle-se2" instance can be tunnelled and Password-Safe-managed but
  # never registered in Entitle. SE2 is the only edition offered license-included.
  description = "RDS Oracle engine: oracle-se2-cdb (default, Entitle-compatible) or oracle-se2 (non-CDB)."

  validation {
    condition     = contains(["oracle-se2-cdb", "oracle-se2"], var.engine)
    error_message = "engine must be oracle-se2-cdb or oracle-se2 (the license-included editions)."
  }
}

variable "engine_version" {
  type        = string
  default     = ""
  description = "Oracle engine version (e.g. 19.0.0.0.ru-2024-10.rur-2024-10.r1). Empty = RDS default."
}

variable "instance_class" {
  type        = string
  default     = "db.t3.small"
  description = "RDS instance class. Oracle needs >= 2 GiB, so no *.micro."
}

variable "allocated_storage" {
  type        = number
  default     = 20
  description = "Allocated storage in GiB (RDS Oracle minimum is 20)"
}

variable "db_name" {
  type        = string
  description = "Oracle DB name — the PDB (cdb) or SID (non-cdb): <=8 alphanumerics, letter first."

  validation {
    condition     = can(regex("^[A-Za-z][A-Za-z0-9]{0,7}$", var.db_name)) && upper(var.db_name) != "RDSCDB"
    error_message = "db_name must be 1-8 alphanumerics starting with a letter, and not RDSCDB."
  }
}

variable "master_username" {
  type        = string
  description = "Master (admin) username"
}

variable "master_password" {
  type        = string
  sensitive   = true
  description = "Master (admin) password, generated by the dashboard at provision (8-30 chars, no / @ \" or space)"
}

variable "db_subnet_group_name" {
  type        = string
  description = "DB subnet group placing the instance in private subnets"
}

variable "vpc_security_group_ids" {
  type        = list(string)
  default     = []
  description = "Security groups controlling access (Gateway/PRA reachability only; must admit 1521)"
}

variable "tags" {
  type        = map(string)
  default     = {}
  description = "Resource tags (workgroup, managed-by)"
}

# ── Resource — always private (no public endpoint) ──────────────────────────
# publicly_accessible = false is load-bearing: the only path in is the PRA tunnel
# (a raw tcp port forward to 1521 until the sra provider ships PRA 26.3's Oracle
# tunnel). No parameter or option group: unlike Postgres/MySQL there is no
# server-side TLS to relax — RDS Oracle's 1521 listener is plain TCP unless an
# SSL option group is attached, and the tcp tunnel forwards whatever it is.

resource "aws_db_instance" "this" {
  identifier     = var.identifier
  engine         = var.engine
  engine_version = var.engine_version != "" ? var.engine_version : null
  instance_class = var.instance_class
  license_model  = "license-included"

  allocated_storage = var.allocated_storage
  db_name           = upper(var.db_name)
  username          = var.master_username
  password          = var.master_password
  port              = 1521

  publicly_accessible    = false
  db_subnet_group_name   = var.db_subnet_group_name
  vpc_security_group_ids = var.vpc_security_group_ids

  skip_final_snapshot = true
  apply_immediately   = true
  deletion_protection = false

  tags = var.tags

  # RDS for Oracle routinely takes 20-40 minutes to create, against the provider's
  # 40-minute default — a create that times out leaves a billable instance the apply
  # then reports as failed. Give it room on both ends.
  timeouts {
    create = "90m"
    delete = "60m"
  }
}

# ── Outputs ─────────────────────────────────────────────────────────────────

output "instance_id" {
  value       = aws_db_instance.this.id
  description = "RDS instance identifier / resource id"
}

output "private_host" {
  value       = aws_db_instance.this.address
  description = "Private endpoint host — reached only via the PRA tunnel"
}

output "port" {
  value       = aws_db_instance.this.port
  description = "Database port (Oracle listener: 1521)"
}

output "service_name" {
  value       = upper(var.db_name)
  description = "Service name a client connects to — the PDB on oracle-se2-cdb"
}
